from .correction import (
    CORRECTION_EVALUATION_PROMPT_TEMPLATE,
    CORRECTION_PROMPT_TEMPLATE,
    CORRECTION_PROMPT_TEMPLATE3,
)
from .resegment import (
    RESEGMENT_CORRECTION_PROMPT_TEMPLATE,
    RESEGMENT_EVALUATION_PROMPT_TEMPLATE,
    RESEGMENT_TRANSLATION_PROMPT_TEMPLATE,
)
from .system import CORRECTION_SYSTEM_PROMPT, CUSTOM_SYSTEM_PROMPT
from .translation import (
    CONTEXT_PROMPT_TEMPLATE,
    EVALUATION_PROMPT_TEMPLATE,
    GLOSSARY_INSTRUCTIONS_EVALUATION,
    GLOSSARY_INSTRUCTIONS_TRANSLATION,
    TRANSLATION_PROMPT_TEMPLATE,
)
from .zoom import ZOOM_CORRECTION_PROMPT_TEMPLATE

__all__ = [
    "TRANSLATION_PROMPT_TEMPLATE",
    "CONTEXT_PROMPT_TEMPLATE",
    "GLOSSARY_INSTRUCTIONS_TRANSLATION",
    "GLOSSARY_INSTRUCTIONS_EVALUATION",
    "EVALUATION_PROMPT_TEMPLATE",
    "CORRECTION_PROMPT_TEMPLATE",
    "CORRECTION_PROMPT_TEMPLATE3",
    "CORRECTION_EVALUATION_PROMPT_TEMPLATE",
    "RESEGMENT_CORRECTION_PROMPT_TEMPLATE",
    "RESEGMENT_EVALUATION_PROMPT_TEMPLATE",
    "RESEGMENT_TRANSLATION_PROMPT_TEMPLATE",
    "CUSTOM_SYSTEM_PROMPT",
    "CORRECTION_SYSTEM_PROMPT",
    "ZOOM_CORRECTION_PROMPT_TEMPLATE",
]
